Mox.defmock(TransportMock, for: TransportBehaviour)
Mox.defmock(MnesiaMock, for: MnesiaBehaviour)
Mox.defmock(Pg2Mock, for: Pg2Behaviour)
Mox.defmock(ManifoldMock, for: ManifoldBehaviour)
Mox.defmock(ProtocolMock, for: Redex.Protocol)
